#pragma once


namespace Client
{
	enum class LEVEL { STATIC, LOADING, LOGO, COURTYARD, ARENA, SHOP, TOOLS, LEVEL_END };
	enum class WEAPON_TYPE { SWORD, STICK, DAGGER, SHILED, WT_END };
	enum class HIT_TYPE { NORMAL, STAGGER, FINCH };
	enum class CAM_MODE { TPS, BOSS, CAM_END };
	enum class COLLIDER_GROUP { PAWN, WEAPON, MONSTER, MONSTER_ATTACK, BOSS, BOSS_ATTACK, ENVIRONMENT, CG_END };
	enum class COLLIDER_ID {
		PLAYER_START,
		PLAYER,
		PLAYER_END,

		WEAPON_START,
		STICK, SWORD, DAGGER, SHILED,
		WEAPON_END,

		MONSTER_START,
		BLOB, WIZARD,
		MONSTER_END,

		MONSTER_ATTACK_START,
		BLOB_ATTACK, WIZARD_ATTACK,
		MONSTER_ATTACK_END,

		BOSS_START,
		BOSS_HEAD, BOSS_WEAK,
		BOSS_END,

		BOSS_ATTACK_START,
		BOSS_ATTACK, BOSS_BULLET, BOSS_BOMB, BOSS_LAGER,
		BOSS_ATTACK_END,

		ENVIRONMENT_START,
		BUSH, GRASS, LADDER, CHECKPOINT, CHEST,
		ENVIRONMENT_END,

		CI_END};
}


