#pragma once


namespace Client
{
	enum class LEVEL { STATIC, LOADING, LOGO, COURTYARD, ARENA, SHOP, TOOLS, LEVEL_END };
	enum class WEAPON_TYPE { SWORD, STICK, DAGGER, SHILED, WT_END };
	enum class CAM_MODE { TPS, BOSS, CAM_END };
	enum class UI_TYPE  { UI2D, UI3D, UI_END };
	enum class COLLIDER_GROUP { PAWN, WEAPON, MONSTER, MONSTER_ATTACK, MONSTER_BULLET, ENVIRONMENT, CG_END };
	enum class COLLIDER_ID {
		PLAYER_START,
		PLAYER,
		PLAYER_END,

		WEAPON_START,
		STICK, SWORD, DAGGER, SHILED,
		WEAPON_END,

		MONSTER_START,
		BLOB, WIZARD, SPIDERTANK_HEAD, SPIDERTANK_WEAK,
		MONSTER_END,

		MONSTER_ATTACK_START,
		BLOB_ATTACK, WIZARD_ATTACK,	SPIDERTANK_ATTACK, 
		MONSTER_ATTACK_END,

		MONSTER_BULLET_START,
		WIZARD_AOE, SPIDERTANK_BULLET, SPIDERTANK_BOMB, SPIDERTANK_LAGER,
		MONSTER_BULLET_END,

		ENVIRONMENT_START,
		BUSH, GRASS, LADDER, CHECKPOINT, CHEST,
		ENVIRONMENT_END,

		CI_END};
}

#define CI_PLAYER( ID )		(COLLIDER_ID::PLAYER_START < ID && COLLIDER_ID::PLAYER_END > ID )
#define CI_WEAPON( ID )		(COLLIDER_ID::WEAPON_START < ID && COLLIDER_ID::WEAPON_END > ID )
#define CI_MONSTER( ID )	(COLLIDER_ID::MONSTER_START < ID && COLLIDER_ID::MONSTER_END > ID )
#define CI_MONSTER_ATTACK( ID )	(COLLIDER_ID::MONSTER_ATTACK_START < ID && COLLIDER_ID::MONSTER_ATTACK_END > ID )
#define CI_MONSTER_BULLET( ID ) (COLLIDER_ID::MONSTER_BULLET_START < ID && COLLIDER_ID::MONSTER_BULLET_END > ID ) 
#define CI_ENVIRONMENT( ID )	(COLLIDER_ID::ENVIRONMENT_START < ID && COLLIDER_ID::ENVIRONMENT_END > ID )