#pragma once


namespace Client
{
	enum EFFECT_PASS { DEFAULT, MAIN, SPRITE, ROTATION, MAIN_BLEND, SPRITE_BLEND, ROTATION_BLEND, MASK, NO_BILLBOARD, PASS_END };
	enum class EFFECT_MOVE { DROP, SPREAD, CHASE, MOVE_END };

	enum class LEVEL { STATIC, LOADING, LOGO, COURTYARD, ARENA, SHOP, TOOLS, LEVEL_END };
	enum class WEAPON_TYPE { SWORD, STICK, DAGGER, SHILED, WT_END };
	enum class ITEM_TYPE { BERRY, BLUEBERRY, COIN_QUESTION, FIRE_CRACKER, SHILED, STICK, DAGGER, SWORD, POTION, COIN, IT_END };
	enum class CAM_MODE { TPS, BOSS, CAM_END };
	enum class UI_TYPE  { UI2D, UI3D, UI_END };
	enum class COLLIDER_GROUP { PAWN, WEAPON, BULLET, MONSTER, MONSTER_ATTACK, MONSTER_BULLET, ENVIRONMENT, ITEM, TRIGGER, CG_END };
	enum class COLLIDER_ID {
		PLAYER_START,
		PLAYER,
		PLAYER_END,

		WEAPON_START,
		STICK, SWORD, DAGGER, SHILED,
		WEAPON_END,

		BULLET_START,
		BULLET_FIRE_CRACKER, BULLET_EXPLOSION,
		BULLET_END,

		MONSTER_START,
		BLOB, WIZARD, SPIDERTANK_HEAD, SPIDERTANK_WEAK,
		MONSTER_END,

		MONSTER_ATTACK_START,
		BLOB_ATTACK, WIZARD_ATTACK,	SPIDERTANK_ATTACK, 
		MONSTER_ATTACK_END,

		MONSTER_BULLET_START,
		WIZARD_AOE, SPIDERTANK_BULLET, SPIDERTANK_BOMB, SPIDERTANK_LAGER,
		MONSTER_BULLET_END,

		ENVIRONMENT_START,
		BUSH, GRASS, LADDER, CHECKPOINT, CHEST, SWITCH,
		ENVIRONMENT_END,

		ITEM_START,
		BERRY, BLUEBERRY, COIN_QUESTION, FIRE_CRACKER, ITEM_SHILED, ITEM_STICK, ITEM_DAGGER, ITEM_SWORD, POTION, COIN,
		ITEM_END,

		TRIGGER_START,
		TRIGGER_COURTYARD, TRIGGER_ARENA, TRIGGER_SHOP, 
		TRIGGER_END,

		CI_END};
}

#define CI_PLAYER( ID )		(COLLIDER_ID::PLAYER_START < ID && COLLIDER_ID::PLAYER_END > ID )
#define CI_WEAPON( ID )		(COLLIDER_ID::WEAPON_START < ID && COLLIDER_ID::WEAPON_END > ID )
#define CI_MONSTER( ID )	(COLLIDER_ID::MONSTER_START < ID && COLLIDER_ID::MONSTER_END > ID )
#define CI_MONSTER_ATTACK( ID )	(COLLIDER_ID::MONSTER_ATTACK_START < ID && COLLIDER_ID::MONSTER_ATTACK_END > ID )
#define CI_MONSTER_BULLET( ID ) (COLLIDER_ID::MONSTER_BULLET_START < ID && COLLIDER_ID::MONSTER_BULLET_END > ID ) 
#define CI_ENVIRONMENT( ID )	(COLLIDER_ID::ENVIRONMENT_START < ID && COLLIDER_ID::ENVIRONMENT_END > ID )
#define CI_ITEM( ID )			(COLLIDER_ID::ITEM_START < ID && COLLIDER_ID::ITEM_END > ID)
#define CI_TRIGGER( ID )		(COLLIDER_ID::TRIGGER_START < ID && COLLIDER_ID::TRIGGER_END > ID)